export const ACTION_TYPES = {
    // Controller and Registration
    CNTRL_LOGIN: "CNTRL_LOGIN",
    CNTRL_REGISTRATION: "CNTRL_REGISTRATION",

    RX_SET_AUTH_BOOL: 'RX_SET_AUTH_BOOL',

    
    // Tasks

    CNTRL_ADD_TASK: 'CNTRL_ADD_TASK', //

    CNTRL_GET_ALL_TASK: 'CNTRL_GET_ALL_TASK',  //
    RX_GET_ALL_TASK: 'RX_GET_ALL_TASK',
    RX_GET_ALL_TASK_PENDING: 'RX_GET_ALL_TASK_PENDING', //
    RX_GET_ALL_TASK_DONE: 'RX_GET_ALL_TASK_DONE', //

    CNTRL_GET_TASK_BY_ID: 'CNTRL_GET_TASK_BY_ID', //
    RX_GET_TASK_BY_ID: 'RX_GET_TASK_BY_ID',
    RX_GET_TASK_BY_ID_PENDING: 'RX_GET_TASK_BY_ID_PENDING', //
    RX_GET_TASK_BY_ID_DONE: 'RX_GET_TASK_BY_ID_DONE' //
}